/**
 * Blackbox Pool Manager
 * 
 * Manages reusable container pools for HTTP-mode (blackbox) and Playwright grading.
 * Instead of creating fresh containers for each grading job, we reuse pre-warmed
 * containers with dependencies already installed.
 * 
 * This eliminates the ~60-120s npm install / pip install overhead per job.
 */

import { spawn, execSync } from 'child_process';
import { mkdir, writeFile, rm } from 'fs/promises';
import { join, dirname } from 'path';
import { tmpdir } from 'os';
import { Mutex } from 'async-mutex';
import { computeDependencyHash } from './container-pool.js';

// ============ Types ============

export interface BlackboxContainer {
    name: string;
    runtime: 'node' | 'python' | 'go' | 'rust';
    image: string;
    workDir: string;
    createdAt: Date;
    lastUsedAt: Date;
    useCount: number;
    isReleased: boolean;
    dependencyHash: string;
}

interface PoolConfig {
    runtime: 'node' | 'python' | 'go' | 'rust';
    image: string;
    dependencies: Record<string, string>;
    /** Files generated by grader (e.g., requirements.txt, package.json) - pre-installed during warmup */
    generatedFiles?: Record<string, string>;
    /** Install command to run after generatedFiles are written */
    installCommand?: string;
    minSize?: number;
    maxSize?: number;
}

// ============ Constants ============

const CONTAINER_PREFIX = 'grader_bb_pool';
const MAX_CONTAINER_USES = 30;        // Recycle after N uses
const CONTAINER_IDLE_TIMEOUT = 10 * 60 * 1000; // 10 minutes
const MAX_POOLS_PER_RUNTIME = 10;
const ACQUIRE_TIMEOUT_MS = 180000;     // 3 minutes (npm install can be slow with parallel I/O)

// ============ Types for Test Runner ============

export interface TestRunnerContainer {
    name: string;
    framework: 'jest' | 'vitest';
    image: string;
    workDir: string;
    createdAt: Date;
    lastUsedAt: Date;
    useCount: number;
    isReleased: boolean;
    poolKey: string;
    dependencyHash: string;
}

// ============ State ============

// Candidate pools keyed by: `${runtime}:${dependencyHash}`
const containerPools = new Map<string, {
    available: BlackboxContainer[];
    inUse: Set<string>;
    config: PoolConfig;
    lastActivityAt: number;
}>();

type TestRunnerFramework = 'jest' | 'vitest';

interface TestRunnerProfileConfig {
    framework: TestRunnerFramework;
    image: string;
    dependencies: Record<string, string>;
}

interface TestRunnerPoolState {
    available: TestRunnerContainer[];
    inUse: Set<string>;
    lastActivityAt: number;
    config: TestRunnerProfileConfig;
}

// Multiple test runner pools keyed by: `${framework}:${image}:${depsHash8}`
const testRunnerPools = new Map<string, TestRunnerPoolState>();

const poolMutex = new Mutex();
const testRunnerMutex = new Mutex();

const TEST_RUNNER_PREFIX = 'grader_bb_test';

const JEST_TEST_RUNNER_DEPS: Record<string, string> = {
    jest: '^29.7.0',
    supertest: '^6.3.3',
};

const VITEST_TEST_RUNNER_DEPS: Record<string, string> = {
    vitest: '^1.6.0',
    '@babel/parser': '^7.24.0',
    '@babel/traverse': '^7.24.0',
};

function getTestRunnerProfile(framework: TestRunnerFramework): Record<string, string> {
    return framework === 'vitest' ? VITEST_TEST_RUNNER_DEPS : JEST_TEST_RUNNER_DEPS;
}

function getTestRunnerPoolKey(params: { framework: TestRunnerFramework; image: string; deps: Record<string, string> }): {
    poolKey: string;
    depsHash: string;
} {
    const depsHash = computeDependencyHash(params.deps);
    const poolKey = `${params.framework}:${params.image}:${depsHash.substring(0, 8)}`;
    return { poolKey, depsHash };
}

// ============ Docker Helpers ============

async function dockerExec(args: string[], timeoutMs: number): Promise<{ stdout: string; stderr: string }> {
    return new Promise((resolve, reject) => {
        const proc = spawn('docker', args, { stdio: ['ignore', 'pipe', 'pipe'] });
        let stdout = '';
        let stderr = '';

        const timer = setTimeout(() => {
            proc.kill('SIGKILL');
            reject(new Error(`Docker timeout: docker ${args.slice(0, 8).join(' ')}...`));
        }, timeoutMs);

        proc.stdout.on('data', (d) => (stdout += d.toString()));
        proc.stderr.on('data', (d) => (stderr += d.toString()));

        proc.on('close', (code) => {
            clearTimeout(timer);
            const exitCode = code ?? 1;
            if (exitCode === 0) return resolve({ stdout, stderr });
            reject(new Error(`Docker command failed (${exitCode}): docker ${args.join(' ')}\n${stdout}\n${stderr}`));
        });

        proc.on('error', (err) => {
            clearTimeout(timer);
            reject(err);
        });
    });
}

async function execInContainer(containerName: string, command: string, timeoutMs = 30000): Promise<string> {
    const { stdout, stderr } = await dockerExec(['exec', containerName, 'sh', '-c', command], timeoutMs);
    return stdout + stderr;
}

// ============ Pool Functions ============

function getPoolKey(runtime: string, deps: Record<string, string>): string {
    const hash = computeDependencyHash(deps);
    return `${runtime}:${hash}`;
}

/**
 * Create a new blackbox container with dependencies pre-installed
 */
async function createContainer(config: PoolConfig): Promise<BlackboxContainer> {
    const hash = computeDependencyHash(config.dependencies);
    const timestamp = Date.now();
    const randomSuffix = Math.random().toString(36).substring(2, 8);
    const name = `${CONTAINER_PREFIX}_${config.runtime}_${hash.substring(0, 8)}_${randomSuffix}`;
    
    // Create host work directory
    const workDir = join(tmpdir(), name);
    await mkdir(workDir, { recursive: true, mode: 0o755 });
    
    console.log(`[BlackboxPool] Creating container: ${name} (${config.runtime})`);
    
    // Prepare dependency files based on runtime
    await prepareDependencyFiles(workDir, config);
    
    // Compute pool key for labeling (enables cross-process discovery!)
    const filesHash = config.generatedFiles 
        ? computeDependencyHash(config.generatedFiles)
        : '';
    const poolKey = `${config.runtime}:${computeDependencyHash(config.dependencies)}:${filesHash.substring(0, 8)}`;
    
    // Container args
    const memoryLimit = 512;
    const dockerArgs = [
        'run', '-d',
        '--name', name,
        '--memory', `${memoryLimit}m`,
        '--memory-swap', `${memoryLimit}m`,
        '--cpus', '1',
        '--pids-limit', '100',
        '-v', `${workDir}:/app:rw`,
        '-w', '/app',
        // Labels for cross-process discovery!
        '--label', `grader.pool=blackbox`,
        '--label', `grader.pool.key=${poolKey}`,
        '--label', `grader.pool.runtime=${config.runtime}`,
        '--label', `grader.pool.workdir=${workDir}`,
        // Note: status tracked via /tmp/.pool-lock file, not label
    ];
    
    // Runtime-specific args
    if (config.runtime === 'node') {
        dockerArgs.push(
            '--user', '1000:1000',
            '--tmpfs', '/tmp:rw,noexec,nosuid,size=100m',
            '--tmpfs', '/home/node/.npm:rw,size=200m'
        );
    } else if (config.runtime === 'python') {
        dockerArgs.push(
            '--tmpfs', '/tmp:rw,noexec,nosuid,size=100m'
        );
    }
    
    dockerArgs.push(config.image, 'tail', '-f', '/dev/null');
    
    await dockerExec(dockerArgs, 30000);
    
    // Create lock file IMMEDIATELY to mark as "in use" (prevents discovery during install!)
    try {
        execSync(`docker exec ${name} touch /tmp/.pool-lock`, { timeout: 5000, stdio: 'ignore' });
    } catch {
        // Ignore, container might be slow to start
    }
    
    // Install dependencies inside container (container is locked during this!)
    await installDependencies(name, config);
    
    const container: BlackboxContainer = {
        name,
        runtime: config.runtime,
        image: config.image,
        workDir,
        createdAt: new Date(),
        lastUsedAt: new Date(),
        useCount: 0,
        isReleased: false,
        dependencyHash: hash,
    };
    
    console.log(`[BlackboxPool] Container created: ${name}`);
    return container;
}

/**
 * Prepare dependency files on host before container creation
 * 
 * Now supports generatedFiles from challenge config!
 * - Node: uses job.dependencies OR generatedFiles['package.json']
 * - Python: uses generatedFiles['requirements.txt']
 * - Go: uses generatedFiles['go.mod']
 * - Rust: uses generatedFiles['Cargo.toml']
 */
async function prepareDependencyFiles(workDir: string, config: PoolConfig): Promise<void> {
    // First: Write all generatedFiles (these come from challenge config)
    if (config.generatedFiles) {
        for (const [filename, content] of Object.entries(config.generatedFiles)) {
            console.log(`[BlackboxPool] Writing generatedFile: ${filename}`);
            const filepath = join(workDir, filename);
            // Create parent directory if needed
            await mkdir(dirname(filepath), { recursive: true }).catch(() => {});
            await writeFile(filepath, content);
        }
    }
    
    // Node fallback: if no package.json in generatedFiles, create from dependencies
    if (config.runtime === 'node') {
        const hasPackageJson = config.generatedFiles?.['package.json'];
        if (!hasPackageJson && Object.keys(config.dependencies).length > 0) {
            const packageJson = {
                name: 'candidate-app',
                version: '1.0.0',
                private: true,
                dependencies: { ...config.dependencies },
            };
            await writeFile(join(workDir, 'package.json'), JSON.stringify(packageJson, null, 2));
        }
    }
}

/**
 * Install dependencies inside the container
 * 
 * Now runs installCommand from challenge config! This pre-installs:
 * - Node: npm install (from package.json in generatedFiles)
 * - Python: pip install -r requirements.txt (from generatedFiles)
 * - Go: go mod download (from generatedFiles)
 * - Rust: cargo build (from generatedFiles)
 */
async function installDependencies(containerName: string, config: PoolConfig): Promise<void> {
    // If we have an explicit installCommand from challenge, use it!
    if (config.installCommand) {
        console.log(`[BlackboxPool] Running installCommand in ${containerName}: ${config.installCommand}`);
        
        // Build environment for the runtime
        let envSetup = '';
        if (config.runtime === 'python') {
            envSetup = 'export HOME=/tmp && export PIP_CACHE_DIR=/tmp/pip-cache && export PIP_TARGET=/app/.packages && export PYTHONPATH=/app/.packages:/app && export PATH=/app/.packages/bin:/usr/local/bin:/usr/bin:/bin && ';
        } else if (config.runtime === 'go') {
            envSetup = 'export GOPATH=/tmp/go && export GOCACHE=/tmp/go-cache && ';
        } else if (config.runtime === 'rust') {
            envSetup = 'export CARGO_HOME=/tmp/.cargo && ';
        }
        
        const fullCmd = `${envSetup}cd /app && ${config.installCommand} 2>&1`;
        await execInContainer(containerName, fullCmd, ACQUIRE_TIMEOUT_MS);
        console.log(`[BlackboxPool] Dependencies installed in ${containerName}`);
        return;
    }
    
    // Fallback: Node installs dependencies if either:
    // - job.dependencies were provided, OR
    // - a generatedFiles package.json exists (common for Playwright/blackbox node challenges)
    if (
        config.runtime === 'node' &&
        (Object.keys(config.dependencies).length > 0 || Boolean(config.generatedFiles?.['package.json']))
    ) {
        console.log(`[BlackboxPool] Installing Node dependencies in ${containerName}...`);
        await execInContainer(containerName, 'cd /app && npm install --legacy-peer-deps 2>&1', ACQUIRE_TIMEOUT_MS);
        console.log(`[BlackboxPool] Dependencies installed in ${containerName}`);
    } else if (config.generatedFiles) {
        // Check if we have manifest files that need installing
        const hasManifest = 
            config.generatedFiles['requirements.txt'] ||
            config.generatedFiles['go.mod'] ||
            config.generatedFiles['Cargo.toml'];
        
        if (hasManifest) {
            const defaultInstallCmd: Record<string, string> = {
                python: 'export HOME=/tmp && export PIP_TARGET=/app/.packages && pip install -r requirements.txt',
                go: 'export GOPATH=/tmp/go && export GOCACHE=/tmp/go-cache && go mod download',
                rust: 'export CARGO_HOME=/tmp/.cargo && cargo build --release',
            };
            const cmd = defaultInstallCmd[config.runtime];
            if (cmd) {
                console.log(`[BlackboxPool] Auto-installing deps for ${config.runtime} in ${containerName}...`);
                await execInContainer(containerName, cmd + ' 2>&1', ACQUIRE_TIMEOUT_MS);
                console.log(`[BlackboxPool] Dependencies installed in ${containerName}`);
            }
        }
    } else {
        console.log(`[BlackboxPool] Container ${containerName} ready (${config.runtime}, no deps to install)`);
    }
}

/**
 * Reset container for reuse - kill processes, clean files, keep deps
 */
async function resetContainer(container: BlackboxContainer): Promise<void> {
    const runtime = container.runtime;
    
    console.log(`[BlackboxPool] Resetting container ${container.name} (${runtime})...`);
    
    // Check processes BEFORE kill (use /proc for slim images without ps)
    try {
        const beforeProcs = execSync(`docker exec ${container.name} sh -c 'for p in /proc/[0-9]*/cmdline; do cat "$p" 2>/dev/null | tr "\\0" " "; echo; done | head -5' 2>/dev/null || true`, { encoding: 'utf-8', timeout: 5000 });
        console.log(`[BlackboxPool] Processes BEFORE reset:\n${beforeProcs}`);
    } catch { /* ignore */ }
    
    // Kill all leftover processes safely.
    // IMPORTANT: never kill PID 1 (tail keepalive) and never kill our own exec shell ($$),
    // otherwise the reset command can terminate itself before cleanup runs.
    // IMPORTANT: keep this as a valid single-line `sh` loop.
    // Do NOT insert `;` right after `do` (i.e. avoid `do; pid=...`) or BusyBox `sh` will error.
    const killCmd =
        'self=$$; ' +
        'for d in /proc/[0-9]*; do ' +
        'pid=${d#/proc/}; ' +
        '[ "$pid" = "1" ] && continue; ' +
        '[ "$pid" = "$self" ] && continue; ' +
        'kill -9 "$pid" 2>/dev/null || true; ' +
        'done; ' +
        'true';
    
    // Clean files but keep dependencies
    const cleanCommands: Record<string, string> = {
        node: 'find /app -mindepth 1 -maxdepth 1 ! -name node_modules ! -name package.json ! -name package-lock.json -exec rm -rf {} +',
        python: 'find /app -mindepth 1 -maxdepth 1 ! -name .packages ! -name requirements.txt ! -name __pycache__ -exec rm -rf {} +',
        go: 'find /app -mindepth 1 -maxdepth 1 ! -name go.mod ! -name go.sum -exec rm -rf {} +',
        rust: 'find /app -mindepth 1 -maxdepth 1 ! -name Cargo.toml ! -name Cargo.lock ! -name target -exec rm -rf {} +',
    };
    
    // NOTE: /tmp contains the cross-process lock file (/tmp/.pool-lock). Do NOT delete it while in-use.
    const tmpCleanCmd = 'find /tmp -mindepth 1 -maxdepth 1 ! -name .pool-lock -exec rm -rf {} + 2>/dev/null || true';

    const resetCmd = [
        'set -e',
        killCmd,
        'sleep 0.3',
        cleanCommands[runtime] || cleanCommands.node,
        tmpCleanCmd,
    ].join(' ; ');
    
    await execInContainer(container.name, resetCmd, 15000);
    
    // Check processes AFTER kill (use /proc for slim images without ps)
    try {
        const afterProcs = execSync(`docker exec ${container.name} sh -c 'for p in /proc/[0-9]*/cmdline; do cat "$p" 2>/dev/null | tr "\\0" " "; echo; done | head -5' 2>/dev/null || true`, { encoding: 'utf-8', timeout: 5000 });
        console.log(`[BlackboxPool] Processes AFTER reset:\n${afterProcs}`);
    } catch { /* ignore */ }
    
    // Log remaining files after cleanup
    try {
        const result = execSync(`docker exec ${container.name} ls -la /app 2>/dev/null || true`, { encoding: 'utf-8', timeout: 5000 });
        console.log(`[BlackboxPool] Files in /app after reset:\n${result}`);
    } catch { /* ignore */ }
    
    container.lastUsedAt = new Date();
    container.useCount++;
    container.isReleased = false;
    
    console.log(`[BlackboxPool] Reset complete for ${container.name}`);
}

/**
 * Destroy a container
 */
async function destroyContainer(container: BlackboxContainer): Promise<void> {
    console.log(`[BlackboxPool] Destroying container: ${container.name}`);
    try {
        execSync(`docker rm -f ${container.name}`, { stdio: 'ignore', timeout: 10000 });
    } catch {
        // Ignore
    }
    await rm(container.workDir, { recursive: true, force: true }).catch(() => {});
}

/**
 * Validate container is healthy
 */
/**
 * Discover available containers from Docker (cross-process discovery)
 * 
 * This enables Worker to find containers warmed by API process!
 * Uses lock file to check availability instead of labels.
 */
async function discoverAvailableContainer(
    poolKey: string, 
    config: PoolConfig
): Promise<BlackboxContainer | null> {
    try {
        // Query Docker for all containers with matching pool key
        const result = execSync(
            `docker ps -q --filter "label=grader.pool=blackbox" --filter "label=grader.pool.key=${poolKey}" 2>/dev/null || true`,
            { encoding: 'utf-8', timeout: 5000 }
        ).trim();
        
        if (!result) return null;
        
        const containerIds = result.split('\n').filter(Boolean);
        if (containerIds.length === 0) return null;
        
        // Check each container for availability (no lock file = available)
        for (const containerId of containerIds) {
            try {
                // Check if lock file exists (if it does, container is in-use)
                const lockCheck = execSync(
                    `docker exec ${containerId} test -f /tmp/.pool-lock && echo locked || echo available`,
                    { encoding: 'utf-8', timeout: 3000 }
                ).trim();
                
                if (lockCheck !== 'available') continue;
                
                // Try to acquire by creating lock file atomically
                execSync(
                    `docker exec ${containerId} sh -c "test ! -f /tmp/.pool-lock && touch /tmp/.pool-lock"`,
                    { timeout: 3000, stdio: 'ignore' }
                );
                
                // Verify we got the lock
                const verifyLock = execSync(
                    `docker exec ${containerId} test -f /tmp/.pool-lock && echo locked || echo available`,
                    { encoding: 'utf-8', timeout: 3000 }
                ).trim();
                
                if (verifyLock !== 'locked') continue;
                
                // Get container info
                const inspectJson = execSync(
                    `docker inspect ${containerId}`,
                    { encoding: 'utf-8', timeout: 5000 }
                );
                const info = JSON.parse(inspectJson)[0];
                const name = info.Name.replace(/^\//, '');
                const workDir = info.Config.Labels['grader.pool.workdir'] || join(tmpdir(), name);
                const runtime = (info.Config.Labels['grader.pool.runtime'] || 'node') as 'node' | 'python' | 'go' | 'rust';
                
                console.log(`[BlackboxPool] Discovered container: ${name} (pool: ${poolKey})`);
                
                return {
                    name,
                    runtime,
                    image: config.image,
                    workDir,
                    createdAt: new Date(info.Created),
                    lastUsedAt: new Date(),
                    useCount: 0,
                    isReleased: false,
                    dependencyHash: computeDependencyHash(config.dependencies),
                };
            } catch {
                // This container didn't work, try next
                continue;
            }
        }
        
        return null;
    } catch {
        // Discovery failed, will create new container
        return null;
    }
}

async function validateContainer(container: BlackboxContainer): Promise<boolean> {
    try {
        const result = execSync(`docker inspect -f '{{.State.Running}}' ${container.name}`, {
            encoding: 'utf-8',
            timeout: 5000,
        }).trim();
        
        if (result !== 'true') return false;
        
        // Check responsive
        await execInContainer(container.name, 'echo ok', 5000);
        
        // Check use count
        if (container.useCount >= MAX_CONTAINER_USES) {
            console.log(`[BlackboxPool] Container ${container.name} reached max uses`);
            return false;
        }
        
        return true;
    } catch {
        return false;
    }
}

/**
 * Acquire a container from pool (or create new one)
 * 
 * With generatedFiles + installCommand, dependencies are PRE-INSTALLED:
 * - Python: requirements.txt already installed → just copy main.py
 * - Node: node_modules ready → just copy src files
 * - Go/Rust: modules cached → just copy source
 */
export async function acquireBlackboxContainer(config: {
    runtime: 'node' | 'python' | 'go' | 'rust';
    image: string;
    dependencies: Record<string, string>;
    generatedFiles?: Record<string, string>;  // Files like requirements.txt, package.json
    installCommand?: string;  // e.g., "pip install -r requirements.txt"
}): Promise<BlackboxContainer> {
    // Include generatedFiles hash in pool key for better cache hit
    const filesHash = config.generatedFiles 
        ? computeDependencyHash(config.generatedFiles)
        : '';
    const poolKey = `${config.runtime}:${computeDependencyHash(config.dependencies)}:${filesHash.substring(0, 8)}`;
    
    return await poolMutex.runExclusive(async () => {
        let pool = containerPools.get(poolKey);
        
        // Create pool if doesn't exist
        if (!pool) {
            pool = {
                available: [],
                inUse: new Set(),
                config: {
                    runtime: config.runtime,
                    image: config.image,
                    dependencies: config.dependencies,
                    generatedFiles: config.generatedFiles,  // <-- Store for warmup!
                    installCommand: config.installCommand,   // <-- Store for warmup!
                },
                lastActivityAt: Date.now(),
            };
            containerPools.set(poolKey, pool);
            console.log(`[BlackboxPool] Created new pool: ${poolKey}`);
        }
        
        pool.lastActivityAt = Date.now();
        
        // Try to get an available container from in-memory pool (deps already installed!)
        while (pool.available.length > 0) {
            const container = pool.available.pop()!;
            
            if (!(await validateContainer(container))) {
                // Container unhealthy, destroy it
                await destroyContainer(container);
                continue;
            }

            // Cross-process safety: mark in-use via /tmp/.pool-lock (in-memory pool alone isn't shared).
            // If we can't acquire the lock, assume another process grabbed it and skip.
            try {
                execSync(
                    `docker exec ${container.name} sh -c "test ! -f /tmp/.pool-lock && touch /tmp/.pool-lock"`,
                    { timeout: 3000, stdio: 'ignore' }
                );
            } catch {
                continue;
            }

            try {
                await resetContainer(container);
            } catch (e) {
                console.warn(`[BlackboxPool] Reset failed for ${container.name}, destroying:`, e);
                await destroyContainer(container);
                continue;
            }

            pool.inUse.add(container.name);
            console.log(`[BlackboxPool] Acquired pooled container: ${container.name} (deps pre-installed ✅)`);
            return container;
        }
        
        // Cross-process discovery: Look for containers created by other processes (e.g., API → Worker)
        const discoveredContainer = await discoverAvailableContainer(poolKey, config);
        if (discoveredContainer) {
            try {
                await resetContainer(discoveredContainer);
            } catch (e) {
                console.warn(`[BlackboxPool] Reset failed for discovered ${discoveredContainer.name}, destroying:`, e);
                await destroyContainer(discoveredContainer);
                // Fall through to create a new container
            }

            if (await validateContainer(discoveredContainer)) {
                pool.inUse.add(discoveredContainer.name);
                console.log(`[BlackboxPool] Discovered container from Docker: ${discoveredContainer.name} (cross-process ✅)`);
                return discoveredContainer;
            }
        }
        
        // No available container, create new one (this installs deps)
        console.log(`[BlackboxPool] No available container, creating new one for ${config.runtime}...`);
        const newContainer = await createContainer(pool.config);
        pool.inUse.add(newContainer.name);
        console.log(`[BlackboxPool] Created new container: ${newContainer.name} (deps installed ✅)`);
        return newContainer;
    });
}

/**
 * Release container back to pool
 */
export async function releaseBlackboxContainer(container: BlackboxContainer): Promise<void> {
    if (container.isReleased) {
        console.warn(`[BlackboxPool] Container ${container.name} already released`);
        return;
    }
    
    container.isReleased = true;
    
    const poolKey = getPoolKey(container.runtime, {});  // We need the full deps but don't have them
    
    await poolMutex.runExclusive(async () => {
        // Find the pool this container belongs to
        for (const [key, pool] of containerPools) {
            if (pool.inUse.has(container.name)) {
                pool.inUse.delete(container.name);
                
                // Check if still healthy
                if (await validateContainer(container)) {
                    pool.available.push(container);
                    
                    // Mark as available (remove lock file for cross-process discovery)
                    try {
                        execSync(
                            `docker exec ${container.name} rm -f /tmp/.pool-lock`,
                            { timeout: 5000, stdio: 'ignore' }
                        );
                    } catch {
                        // Ignore
                    }
                    
                    console.log(`[BlackboxPool] Released container: ${container.name} (available: ${pool.available.length})`);
                } else {
                    await destroyContainer(container);
                }
                return;
            }
        }
        
        // Container not in any pool, just destroy
        console.warn(`[BlackboxPool] Container ${container.name} not found in any pool, destroying`);
        await destroyContainer(container);
    });
}

/**
 * Get pool status
 */
export function getBlackboxPoolStatus(): {
    pools: Array<{
        key: string;
        runtime: string;
        available: number;
        inUse: number;
    }>;
    totalContainers: number;
} {
    const pools: Array<{ key: string; runtime: string; available: number; inUse: number }> = [];
    let totalContainers = 0;
    
    for (const [key, pool] of containerPools) {
        pools.push({
            key,
            runtime: pool.config.runtime,
            available: pool.available.length,
            inUse: pool.inUse.size,
        });
        totalContainers += pool.available.length + pool.inUse.size;
    }
    
    return { pools, totalContainers };
}

/**
 * Cleanup idle pools
 */
export async function cleanupIdleBlackboxPools(): Promise<number> {
    let cleanedCount = 0;
    
    await poolMutex.runExclusive(async () => {
        const now = Date.now();
        
        for (const [key, pool] of containerPools) {
            // Check if pool is idle
            if (pool.inUse.size === 0 && now - pool.lastActivityAt > CONTAINER_IDLE_TIMEOUT) {
                console.log(`[BlackboxPool] Cleaning up idle pool: ${key}`);
                
                for (const container of pool.available) {
                    await destroyContainer(container);
                    cleanedCount++;
                }
                
                containerPools.delete(key);
            }
        }
    });
    
    if (cleanedCount > 0) {
        console.log(`[BlackboxPool] Cleaned up ${cleanedCount} idle containers`);
    }
    
    return cleanedCount;
}

/**
 * Drain all pools (shutdown)
 */
export async function drainBlackboxPools(): Promise<void> {
    console.log('[BlackboxPool] Draining all pools...');
    
    await poolMutex.runExclusive(async () => {
        for (const [key, pool] of containerPools) {
            for (const container of pool.available) {
                await destroyContainer(container);
            }
            // Note: in-use containers will be cleaned up when they're released
        }
        containerPools.clear();
    });
    
    console.log('[BlackboxPool] All pools drained');
}

/**
 * Initialize blackbox pool system
 */
export async function initializeBlackboxPool(): Promise<void> {
    console.log('[BlackboxPool] Initializing...');
    
    // Cleanup orphaned containers from previous runs
    try {
        const result = execSync(
            `docker ps -aq --filter "name=${CONTAINER_PREFIX}" 2>/dev/null || true`,
            { encoding: 'utf-8', timeout: 10000 }
        ).trim();
        
        if (result) {
            const containers = result.split('\n').filter(Boolean);
            console.log(`[BlackboxPool] Cleaning up ${containers.length} orphaned containers...`);
            for (const id of containers) {
                try {
                    execSync(`docker rm -f ${id}`, { stdio: 'ignore', timeout: 5000 });
                } catch {
                    // Ignore
                }
            }
        }
    } catch {
        // Ignore
    }
    
    console.log('[BlackboxPool] Initialized');
    
    // Also cleanup orphaned test runner containers
    try {
        const result = execSync(
            `docker ps -aq --filter "name=${TEST_RUNNER_PREFIX}" 2>/dev/null || true`,
            { encoding: 'utf-8', timeout: 10000 }
        ).trim();
        
        if (result) {
            const containers = result.split('\n').filter(Boolean);
            console.log(`[BlackboxPool] Cleaning up ${containers.length} orphaned test runners...`);
            for (const id of containers) {
                try {
                    execSync(`docker rm -f ${id}`, { stdio: 'ignore', timeout: 5000 });
                } catch {
                    // Ignore
                }
            }
        }
    } catch {
        // Ignore
    }
}

// ============ Test Runner Pool Functions ============

/**
 * Create a test runner container with framework deps pre-installed
 */
async function createTestRunnerContainer(config: TestRunnerProfileConfig): Promise<TestRunnerContainer> {
    const timestamp = Date.now();
    const randomSuffix = Math.random().toString(36).substring(2, 8);
    const deps = config.dependencies;
    const { poolKey, depsHash } = getTestRunnerPoolKey({ framework: config.framework, image: config.image, deps });
    const name = `${TEST_RUNNER_PREFIX}_${config.framework}_${depsHash.substring(0, 8)}_${randomSuffix}_${timestamp}`;
    
    // Create host work directory
    const workDir = join(tmpdir(), name);
    await mkdir(workDir, { recursive: true, mode: 0o755 });
    
    console.log(`[BlackboxPool] Creating test runner: ${name} (${config.framework})`);
    
    // Create package.json with test dependencies
    const baseScripts: Record<string, string> =
        config.framework === 'vitest'
            ? {
                  // Vitest v1.6 does not support `--threads`; enforce serial execution via workers + file parallelism.
                  test: 'vitest run --pool=threads --no-file-parallelism --maxWorkers=1 --minWorkers=1 --reporter=junit --outputFile=results.xml',
              }
            : { test: 'jest --json --outputFile=results.json' };

    const packageJson: Record<string, unknown> = {
        name: 'grader-test-runner',
        version: '1.0.0',
        private: true,
        scripts: baseScripts,
        devDependencies: { ...deps },
    };

    if (config.framework === 'vitest') {
        // Vitest tests/harness are authored as ESM by default.
        packageJson.type = 'module';
    } else {
        // Jest runner stays CommonJS-friendly by default (do not force ESM via `type: module`).
        (packageJson as any).jest = {
            testEnvironment: 'node',
            testTimeout: 30000,
            verbose: true,
        };
    }
    await writeFile(join(workDir, 'package.json'), JSON.stringify(packageJson, null, 2));
    
    // Container args with labels for cross-process discovery
    const dockerArgs = [
        'run', '-d',
        '--name', name,
        '--memory', '512m',
        '--memory-swap', '512m',
        '--cpus', '1',
        '--pids-limit', '100',
        '-v', `${workDir}:/app:rw`,
        '-w', '/app',
        '--user', '1000:1000',
        '--tmpfs', '/tmp:rw,noexec,nosuid,size=100m',
        '--tmpfs', '/home/node/.npm:rw,size=200m',
        // Labels for cross-process discovery
        '--label', 'grader.pool=testrunner',
        '--label', `grader.pool.framework=${config.framework}`,
        '--label', `grader.pool.key=${poolKey}`,
        '--label', `grader.pool.image=${config.image}`,
        '--label', `grader.pool.workdir=${workDir}`,
        // Note: status tracked via /tmp/.pool-lock file, not label
        config.image,
        'tail', '-f', '/dev/null',
    ];
    
    await dockerExec(dockerArgs, 30000);
    
    // Create lock file IMMEDIATELY to mark as "in use" (prevents discovery during npm install!)
    try {
        execSync(`docker exec ${name} touch /tmp/.pool-lock`, { timeout: 5000, stdio: 'ignore' });
    } catch {
        // Ignore
    }
    
    // Pre-install test dependencies (container is locked during this!)
    console.log(`[BlackboxPool] Installing test dependencies in ${name}...`);
    await execInContainer(name, 'npm install --legacy-peer-deps 2>&1', ACQUIRE_TIMEOUT_MS);
    
    console.log(`[BlackboxPool] Test runner ready: ${name}`);
    
    return {
        name,
        framework: config.framework,
        image: config.image,
        workDir,
        createdAt: new Date(),
        lastUsedAt: new Date(),
        useCount: 0,
        isReleased: false,
        poolKey,
        dependencyHash: depsHash,
    };
}

/**
 * Reset test runner container for reuse
 */
async function resetTestRunnerContainer(container: TestRunnerContainer): Promise<void> {
    // Kill any running processes and clean test files (keep node_modules)
    // NOTE: /tmp contains the cross-process lock file (/tmp/.pool-lock). Do NOT delete it while in-use.
    // IMPORTANT: keep this as a valid single-line `sh` loop (avoid `do; pid=...`).
    const killCmd =
        'self=$$; ' +
        'for d in /proc/[0-9]*; do ' +
        'pid=${d#/proc/}; ' +
        '[ "$pid" = "1" ] && continue; ' +
        '[ "$pid" = "$self" ] && continue; ' +
        'kill -9 "$pid" 2>/dev/null || true; ' +
        'done; ' +
        'true';

    const cleanCmd =
        'find /app -mindepth 1 -maxdepth 1 ! -name node_modules ! -name package.json ! -name package-lock.json -exec rm -rf {} +';
    const tmpCleanCmd = 'find /tmp -mindepth 1 -maxdepth 1 ! -name .pool-lock -exec rm -rf {} + 2>/dev/null || true';

    await execInContainer(container.name, `set -e ; ${killCmd} ; ${cleanCmd} ; ${tmpCleanCmd}`, 15000);
    
    container.lastUsedAt = new Date();
    container.useCount++;
    container.isReleased = false;
}

/**
 * Validate test runner is healthy
 */
async function validateTestRunner(container: TestRunnerContainer): Promise<boolean> {
    try {
        const result = execSync(`docker inspect -f '{{.State.Running}}' ${container.name}`, {
            encoding: 'utf-8',
            timeout: 5000,
        }).trim();
        
        if (result !== 'true') return false;
        
        // Check responsive
        await execInContainer(container.name, 'echo ok', 5000);
        
        // Check use count
        if (container.useCount >= MAX_CONTAINER_USES) {
            console.log(`[BlackboxPool] Test runner ${container.name} reached max uses`);
            return false;
        }
        
        return true;
    } catch {
        return false;
    }
}

/**
 * Destroy test runner container
 */
async function destroyTestRunner(container: TestRunnerContainer): Promise<void> {
    console.log(`[BlackboxPool] Destroying test runner: ${container.name}`);
    try {
        execSync(`docker rm -f ${container.name}`, { stdio: 'ignore', timeout: 10000 });
    } catch {
        // Ignore
    }
    await rm(container.workDir, { recursive: true, force: true }).catch(() => {});
}

/**
 * Discover available test runner from Docker (cross-process discovery)
 * Uses lock file to check availability.
 */
async function discoverAvailableTestRunner(params: {
    poolKey: string;
    framework: TestRunnerFramework;
    image: string;
    depsHash: string;
}): Promise<TestRunnerContainer | null> {
    try {
        const { poolKey } = params;

        // Query Docker for all test runners with matching pool key
        const result = execSync(
            `docker ps -q --filter "label=grader.pool=testrunner" --filter "label=grader.pool.key=${poolKey}" 2>/dev/null || true`,
            { encoding: 'utf-8', timeout: 5000 }
        ).trim();
        
        if (!result) return null;
        
        const containerIds = result.split('\n').filter(Boolean);
        if (containerIds.length === 0) return null;
        
        // Check each container for availability (no lock file = available)
        for (const containerId of containerIds) {
            try {
                // Check if lock file exists
                const lockCheck = execSync(
                    `docker exec ${containerId} test -f /tmp/.pool-lock && echo locked || echo available`,
                    { encoding: 'utf-8', timeout: 3000 }
                ).trim();
                
                if (lockCheck !== 'available') continue;
                
                // Try to acquire by creating lock file
                execSync(
                    `docker exec ${containerId} sh -c "test ! -f /tmp/.pool-lock && touch /tmp/.pool-lock"`,
                    { timeout: 3000, stdio: 'ignore' }
                );
                
                // Get container info
                const inspectJson = execSync(
                    `docker inspect ${containerId}`,
                    { encoding: 'utf-8', timeout: 5000 }
                );
                const info = JSON.parse(inspectJson)[0];
                const name = info.Name.replace(/^\//, '');
                const labels = (info.Config && info.Config.Labels) || {};
                const workDir = labels['grader.pool.workdir'] || join(tmpdir(), name);
                const framework = (labels['grader.pool.framework'] as TestRunnerFramework) || params.framework;
                const image = (labels['grader.pool.image'] as string) || params.image;
                const discoveredPoolKey = (labels['grader.pool.key'] as string) || poolKey;
                
                console.log(`[BlackboxPool] Discovered test runner from Docker: ${name}`);
                
                return {
                    name,
                    framework,
                    image,
                    workDir,
                    createdAt: new Date(info.Created),
                    lastUsedAt: new Date(),
                    useCount: 0,
                    isReleased: false,
                    poolKey: discoveredPoolKey,
                    dependencyHash: params.depsHash,
                };
            } catch {
                continue;
            }
        }
        
        return null;
    } catch {
        return null;
    }
}

/**
 * Acquire a test runner container from pool
 */
export async function acquireTestRunner(
    arg: string | { framework: TestRunnerFramework; image?: string } = 'node:20-alpine'
): Promise<TestRunnerContainer> {
    return await testRunnerMutex.runExclusive(async () => {
        const framework: TestRunnerFramework = typeof arg === 'string' ? 'jest' : arg.framework;
        const image: string = typeof arg === 'string' ? arg : arg.image || 'node:20-alpine';
        const deps = getTestRunnerProfile(framework);
        const { poolKey, depsHash } = getTestRunnerPoolKey({ framework, image, deps });

        let pool = testRunnerPools.get(poolKey);
        if (!pool) {
            pool = {
                available: [],
                inUse: new Set(),
                lastActivityAt: Date.now(),
                config: { framework, image, dependencies: deps },
            };
            testRunnerPools.set(poolKey, pool);
        } else {
            pool.lastActivityAt = Date.now();
        }
        
        // Try to get an available container from the matching pool (in-memory)
        while (pool.available.length > 0) {
            const container = pool.available.pop()!;
            
            if (container.image !== image) {
                await destroyTestRunner(container);
                continue;
            }
            if (container.framework !== framework) {
                await destroyTestRunner(container);
                continue;
            }
            if (container.poolKey !== poolKey) {
                await destroyTestRunner(container);
                continue;
            }

            if (!(await validateTestRunner(container))) {
                await destroyTestRunner(container);
                continue;
            }

            // Cross-process safety: lock it while in-use.
            try {
                execSync(
                    `docker exec ${container.name} sh -c "test ! -f /tmp/.pool-lock && touch /tmp/.pool-lock"`,
                    { timeout: 3000, stdio: 'ignore' }
                );
            } catch {
                continue;
            }

            try {
                await resetTestRunnerContainer(container);
            } catch (e) {
                console.warn(`[BlackboxPool] Reset failed for test runner ${container.name}, destroying:`, e);
                await destroyTestRunner(container);
                continue;
            }

            pool.inUse.add(container.name);
            console.log(`[BlackboxPool] Acquired test runner: ${container.name} (from pool ✅)`);
            return container;
        }
        
        // Cross-process discovery: Look for containers created by other processes
        const discovered = await discoverAvailableTestRunner({ poolKey, framework, image, depsHash });
        if (discovered) {
            try {
                await resetTestRunnerContainer(discovered);
            } catch (e) {
                console.warn(`[BlackboxPool] Reset failed for discovered test runner ${discovered.name}, destroying:`, e);
                await destroyTestRunner(discovered);
                // Fall through to create a new one
            }

            if (await validateTestRunner(discovered)) {
                // Ensure correct metadata on discovered container
                discovered.framework = framework;
                discovered.image = image;
                discovered.poolKey = poolKey;
                discovered.dependencyHash = depsHash;

                pool.inUse.add(discovered.name);
                console.log(`[BlackboxPool] Acquired test runner: ${discovered.name} (cross-process ✅)`);
                return discovered;
            }
        }
        
        // No available container, create new one
        console.log(`[BlackboxPool] Creating new test runner for ${framework}:${image}...`);
        const newContainer = await createTestRunnerContainer(pool.config);
        pool.inUse.add(newContainer.name);
        return newContainer;
    });
}

/**
 * Release test runner back to pool
 */
export async function releaseTestRunner(container: TestRunnerContainer): Promise<void> {
    if (container.isReleased) {
        console.warn(`[BlackboxPool] Test runner ${container.name} already released`);
        return;
    }
    
    container.isReleased = true;
    
    await testRunnerMutex.runExclusive(async () => {
        const poolKey = container.poolKey;
        const pool = testRunnerPools.get(poolKey);
        if (!pool) {
            // If pool missing (process restart), create minimal pool state for correct bookkeeping
            const framework = container.framework || 'jest';
            const deps = getTestRunnerProfile(framework);
            testRunnerPools.set(poolKey, {
                available: [],
                inUse: new Set(),
                lastActivityAt: Date.now(),
                config: { framework, image: container.image, dependencies: deps },
            });
        }
        const ensuredPool = testRunnerPools.get(poolKey)!;

        ensuredPool.inUse.delete(container.name);
        
        if (await validateTestRunner(container)) {
            ensuredPool.available.push(container);
            
            // Mark as available (remove lock file for cross-process discovery)
            try {
                execSync(
                    `docker exec ${container.name} rm -f /tmp/.pool-lock`,
                    { timeout: 5000, stdio: 'ignore' }
                );
            } catch {
                // Ignore
            }
            
            console.log(`[BlackboxPool] Released test runner: ${container.name} (available: ${ensuredPool.available.length})`);
        } else {
            await destroyTestRunner(container);
        }
    });
}

/**
 * Warm up test runner pool - TRULY PARALLEL (creates directly, no mutex)
 */
export async function warmTestRunnerPool(
    countOrConfig: number | { count?: number; framework: TestRunnerFramework; image?: string } = 3,
    imageArg: string = 'node:20-alpine'
): Promise<number> {
    const framework: TestRunnerFramework =
        typeof countOrConfig === 'number' ? 'jest' : countOrConfig.framework;
    const count: number = typeof countOrConfig === 'number' ? countOrConfig : countOrConfig.count ?? 3;
    const image: string = typeof countOrConfig === 'number' ? imageArg : countOrConfig.image || 'node:20-alpine';

    const deps = getTestRunnerProfile(framework);
    const { poolKey } = getTestRunnerPoolKey({ framework, image, deps });

    let pool = testRunnerPools.get(poolKey);
    if (!pool) {
        pool = {
            available: [],
            inUse: new Set(),
            lastActivityAt: Date.now(),
            config: { framework, image, dependencies: deps },
        };
        testRunnerPools.set(poolKey, pool);
    }

    console.log(`[BlackboxPool] Warming ${count} test runners in PARALLEL (${framework}:${image})...`);
    
    // Create all containers in parallel (directly, not through acquire)
    const results = await Promise.all(
        Array.from({ length: count }, async (_, i) => {
            try {
                const container = await createTestRunnerContainer(pool!.config);
                return container;
            } catch (e) {
                console.warn(`[BlackboxPool] Failed to warm test runner ${i}:`, e);
                return null;
            }
        })
    );
    
    const containers = results.filter((c): c is TestRunnerContainer => c !== null);
    
    // Add to pool and release (remove lock files)
    for (const container of containers) {
        // Remove lock file to make available
        try {
            execSync(`docker exec ${container.name} rm -f /tmp/.pool-lock`, { timeout: 5000, stdio: 'ignore' });
        } catch { /* ignore */ }
        pool.available.push(container);
    }
    
    console.log(`[BlackboxPool] Warmed ${containers.length} test runners`);
    return containers.length;
}

/**
 * Warm up blackbox containers - TRULY PARALLEL (creates directly, no mutex)
 */
export async function warmBlackboxContainers(config: {
    runtime: 'node' | 'python' | 'go' | 'rust';
    image: string;
    dependencies: Record<string, string>;
    generatedFiles?: Record<string, string>;
    installCommand?: string;
    count?: number;
}): Promise<number> {
    const count = config.count || 5;
    console.log(`[BlackboxPool] Warming ${count} blackbox containers for ${config.runtime} in PARALLEL...`);
    
    // Ensure pool exists
    const filesHash = config.generatedFiles 
        ? computeDependencyHash(config.generatedFiles)
        : '';
    const poolKey = `${config.runtime}:${computeDependencyHash(config.dependencies)}:${filesHash.substring(0, 8)}`;
    
    let pool = containerPools.get(poolKey);
    if (!pool) {
        pool = {
            available: [],
            inUse: new Set(),
            config: {
                runtime: config.runtime,
                image: config.image,
                dependencies: config.dependencies,
                generatedFiles: config.generatedFiles,
                installCommand: config.installCommand,
            },
            lastActivityAt: Date.now(),
        };
        containerPools.set(poolKey, pool);
        console.log(`[BlackboxPool] Created pool: ${poolKey}`);
    }
    
    // Create all containers in TRUE PARALLEL (no mutex serialization!)
    const results = await Promise.all(
        Array.from({ length: count }, async (_, i) => {
            try {
                const container = await createContainer(pool!.config);
                return container;
            } catch (e) {
                console.warn(`[BlackboxPool] Failed to warm container ${i}:`, e);
                return null;
            }
        })
    );
    
    const containers = results.filter((c): c is BlackboxContainer => c !== null);
    
    // Add to pool and release (remove lock files to make available for cross-process discovery)
    for (const container of containers) {
        try {
            execSync(`docker exec ${container.name} rm -f /tmp/.pool-lock`, { timeout: 5000, stdio: 'ignore' });
        } catch { /* ignore */ }
        pool.available.push(container);
    }
    
    console.log(`[BlackboxPool] Warmed ${containers.length} blackbox containers (${config.runtime})`);
    return containers.length;
}

/**
 * Get test runner pool status
 */
export function getTestRunnerPoolStatus(): {
    available: number;
    inUse: number;
} {
    let available = 0;
    let inUse = 0;
    for (const p of testRunnerPools.values()) {
        available += p.available.length;
        inUse += p.inUse.size;
    }
    return {
        available,
        inUse,
    };
}

