/**
 * Pool Warmer Service
 * 
 * Pre-warms container pools before exam start.
 * Triggered automatically 15 minutes before scheduled exam start,
 * or manually via admin API.
 */

import { db } from './db.js';
import { exams } from '@exam-platform/database';
import { eq } from 'drizzle-orm';
import { redisConnection } from './redis.js';
import {
    getTestRunnerPool,
    getCandidatePool,
    calculatePoolSize,
    getPoolStatus,
    type PoolStats,
} from './container-pool.js';
import {
    warmBlackboxContainers,
    warmTestRunnerPool,
} from './blackbox-pool-manager.js';

// ============ Types ============

export interface WarmupConfig {
    examId: string;
    expectedCandidates: number;
    runnerMode?: string;
    runtime: string;
    challengeDependencies: Record<string, string>;
    candidateImage?: string;  // For blackbox pool warming
    testsImage?: string;      // For blackbox test runner warming (jest/vitest)
    /** Files generated by grader (e.g., requirements.txt) - pre-installed during warmup */
    generatedFiles?: Record<string, string>;
    /** Install command from challenge (e.g., "pip install -r requirements.txt") */
    installCommand?: string;
    customPoolSize?: {
        testRunners?: number;
        candidates?: number;
    };
}

export interface WarmupResult {
    success: boolean;
    examId: string;
    testRunners: number;
    candidateContainers: number;
    warmupTimeMs: number;
    error?: string;
}

// Redis keys for warmup tracking
const WARMUP_LOCK_PREFIX = 'pool_warmup_lock:';
const WARMUP_STATUS_PREFIX = 'pool_warmup_status:';

// ============ Main Warmup Function ============

/**
 * Warm container pool for an exam
 * 
 * This pre-creates containers and installs dependencies so grading
 * can happen instantly when students submit.
 */
export async function warmPoolForExam(config: WarmupConfig): Promise<WarmupResult> {
    const startTime = Date.now();
    const { examId, expectedCandidates, runtime, challengeDependencies, candidateImage, customPoolSize } = config;

    console.log(`🔥 [Warmer] Starting warmup for exam ${examId}`);
    console.log(`   Expected candidates: ${expectedCandidates}`);
    console.log(`   Runtime: ${runtime}`);
    console.log(`   Candidate image: ${candidateImage || 'default'}`);
    console.log(`   Dependencies: ${Object.keys(challengeDependencies).length} packages`);

    // Acquire distributed lock to prevent duplicate warmups
    const lockKey = `${WARMUP_LOCK_PREFIX}${examId}`;
    const lockAcquired = await redisConnection.set(lockKey, '1', 'EX', 300, 'NX');

    if (!lockAcquired) {
        console.log(`[Warmer] Warmup already in progress for exam ${examId}`);
        return {
            success: false,
            examId,
            testRunners: 0,
            candidateContainers: 0,
            warmupTimeMs: 0,
            error: 'Warmup already in progress',
        };
    }

    try {
        // Calculate pool sizes
        const autoSize = calculatePoolSize(expectedCandidates);
        const poolSize = {
            testRunners: customPoolSize?.testRunners || autoSize.testRunners,
            candidates: customPoolSize?.candidates || autoSize.candidates,
        };

        const mode = config.runnerMode;
        const isBlackboxMode = mode === 'http' || mode === 'playwright' || mode === 'ui_jsdom';
        const isLegacyMode = !isBlackboxMode;

        console.log(`   Pool size: ${poolSize.testRunners} test runners, ${poolSize.candidates} candidates`);

        const imageMap: Record<string, string> = {
            node: 'node:20-alpine',
            python: 'python:3.11-slim',
            go: 'golang:1.21-alpine',
            rust: 'rust:1.75-alpine',
        };
        const candidateImage = config.candidateImage || imageMap[runtime] || imageMap.node;
        // NOTE: testsImage is only relevant for node-based blackbox test runners (http/ui_jsdom).
        // Playwright tests run in a Playwright image and are not pooled here.
        const testsImage = imageMap.node;
        const blackboxRuntime = runtime === 'react' ? 'node' : runtime;

        // ⚡ PARALLEL WARMUP - All pools warm simultaneously!
        console.log('[Warmer] Starting parallel warmup...');
        
        // Results will be collected here
        const warmupResults = {
            testRunners: 0,
            blackboxContainers: 0,
            httpTestRunners: 0,
            httpTestRunnerFramework: 'jest' as 'jest' | 'vitest',
            legacyCandidates: 0,
        };
        
        const warmupPromises = [
            // 1. Warm legacy test runner pool (for Jest mode)
            (async () => {
                if (!isLegacyMode) {
                    warmupResults.testRunners = 0;
                    console.log('[Warmer] [1/4] Skipping legacy test runner warmup (blackbox runner)');
                    return;
                }
                console.log('[Warmer] [1/4] Warming legacy test runner pool...');
                const testRunnerPool = await getTestRunnerPool(challengeDependencies);
                const containers = await Promise.all(
                    Array.from({ length: Math.min(poolSize.testRunners, 5) }, async (_, i) => {
                        try {
                            return await testRunnerPool.acquire(120000);
                        } catch (e) {
                            console.warn(`[Warmer] Failed to acquire test runner ${i}:`, e);
                            return null;
                        }
                    })
                );
                const validContainers = containers.filter(Boolean);
                for (const container of validContainers) {
                    if (container) await testRunnerPool.release(container);
                }
                warmupResults.testRunners = validContainers.length;
                console.log(`[Warmer] [1/4] ✅ Warmed ${validContainers.length} legacy test runners`);
            })(),

            // 2. Warm blackbox containers (candidate containers with deps pre-installed) - TRUE PARALLEL!
            (async () => {
                if (!isBlackboxMode) {
                    warmupResults.blackboxContainers = 0;
                    console.log('[Warmer] [2/4] Skipping blackbox container warmup (legacy runner)');
                    return;
                }
                console.log(`[Warmer] [2/4] Warming blackbox pool for ${blackboxRuntime}...`);
                const count = await warmBlackboxContainers({
                    runtime: blackboxRuntime as 'node' | 'python' | 'go' | 'rust',
                    image: candidateImage,
                    dependencies: challengeDependencies,
                    generatedFiles: config.generatedFiles,
                    installCommand: config.installCommand,
                    count: Math.min(poolSize.candidates, 5),
                });
                warmupResults.blackboxContainers = count;
                if (config.generatedFiles) {
                    console.log(`[Warmer] [2/4] ✅ Warmed ${count} blackbox containers (deps: ${Object.keys(config.generatedFiles).join(', ')})`);
                } else {
                    console.log(`[Warmer] [2/4] ✅ Warmed ${count} blackbox containers`);
                }
            })(),

            // 3. Warm blackbox test runners (http -> jest, ui_jsdom -> vitest). Playwright doesn't use this pool.
            (async () => {
                const mode = config.runnerMode;
                if (mode !== 'http' && mode !== 'ui_jsdom') {
                    warmupResults.httpTestRunners = 0;
                    warmupResults.httpTestRunnerFramework = 'jest';
                    console.log('[Warmer] [3/4] Skipping blackbox test runner warmup (not http/ui_jsdom)');
                    return;
                }

                const framework = mode === 'ui_jsdom' ? 'vitest' : 'jest';
                const runnerImage = config.testsImage || imageMap.node;
                warmupResults.httpTestRunnerFramework = framework;
                console.log(`[Warmer] [3/4] Warming ${framework} test runner pool...`);
                const warmCount = await warmTestRunnerPool({
                    framework,
                    count: Math.min(poolSize.testRunners, 5),
                    image: runnerImage,
                });
                warmupResults.httpTestRunners = warmCount;
                console.log(`[Warmer] [3/4] ✅ Warmed ${warmCount} ${framework} test runners`);
            })(),

            // 4. Warm legacy candidate pool (for Jest-mode challenges)
            (async () => {
                if (!isLegacyMode) {
                    warmupResults.legacyCandidates = 0;
                    console.log('[Warmer] [4/4] Skipping legacy candidate warmup (blackbox runner)');
                    return;
                }
                console.log(`[Warmer] [4/4] Warming legacy candidate pool for ${runtime}...`);
                const candidatePool = await getCandidatePool(runtime);
                const containers = await Promise.all(
                    Array.from({ length: Math.min(poolSize.candidates, 5) }, async (_, i) => {
                        try {
                            return await candidatePool.acquire(120000);
                        } catch (e) {
                            console.warn(`[Warmer] Failed to acquire candidate ${i}:`, e);
                            return null;
                        }
                    })
                );
                const validContainers = containers.filter(Boolean);
                for (const container of validContainers) {
                    if (container) await candidatePool.release(container);
                }
                warmupResults.legacyCandidates = validContainers.length;
                console.log(`[Warmer] [4/4] ✅ Warmed ${validContainers.length} legacy candidates`);
            })(),
        ];

        // Wait for all warmup tasks to complete
        await Promise.all(warmupPromises);
        console.log('[Warmer] ✅ All pools warmed in parallel!');

        // Update exam poolWarmedAt (optional - column may not exist if migration not run)
        try {
            await db
                .update(exams)
                .set({ poolWarmedAt: new Date() } as Record<string, unknown>)
                .where(eq(exams.id, examId));
        } catch (dbErr) {
            // Column might not exist yet - that's okay, we use Redis for tracking
            console.warn('[Warmer] Could not update poolWarmedAt (run migration to enable):', dbErr);
        }

        // Store warmup status in Redis
        const statusKey = `${WARMUP_STATUS_PREFIX}${examId}`;
        await redisConnection.set(
            statusKey,
            JSON.stringify({
                warmedAt: new Date().toISOString(),
                testRunners: warmupResults.testRunners,
                blackboxContainers: warmupResults.blackboxContainers,
                httpTestRunners: warmupResults.httpTestRunners,
                httpTestRunnerFramework: warmupResults.httpTestRunnerFramework,
                candidates: warmupResults.legacyCandidates,
                runtime,
                runnerMode: config.runnerMode || null,
            }),
            'EX',
            24 * 60 * 60 // 24h TTL
        );

        const warmupTimeMs = Date.now() - startTime;

        console.log(`✅ [Warmer] Warmup complete for exam ${examId} in ${warmupTimeMs}ms`);
        console.log(`   Legacy test runners: ${warmupResults.testRunners}`);
        console.log(`   Blackbox containers: ${warmupResults.blackboxContainers} (deps pre-installed)`);
        console.log(`   Blackbox test runners: ${warmupResults.httpTestRunners} (${warmupResults.httpTestRunnerFramework})`);
        console.log(`   Legacy candidates: ${warmupResults.legacyCandidates}`);

        return {
            success: true,
            examId,
            testRunners: warmupResults.testRunners + warmupResults.httpTestRunners,
            candidateContainers: warmupResults.blackboxContainers + warmupResults.legacyCandidates,
            warmupTimeMs,
        };
    } catch (error) {
        console.error(`❌ [Warmer] Warmup failed for exam ${examId}:`, error);
        return {
            success: false,
            examId,
            testRunners: 0,
            candidateContainers: 0,
            warmupTimeMs: Date.now() - startTime,
            error: String(error),
        };
    } finally {
        // Release lock
        await redisConnection.del(lockKey);
    }
}

/**
 * Check if pool is already warm for an exam
 */
export async function isExamPoolWarm(examId: string): Promise<boolean> {
    const statusKey = `${WARMUP_STATUS_PREFIX}${examId}`;
    const status = await redisConnection.get(statusKey);
    return status !== null;
}

/**
 * Get warmup status for an exam
 */
export async function getExamWarmupStatus(examId: string): Promise<{
    isWarm: boolean;
    warmedAt?: string;
    testRunners?: number;
    candidates?: number;
    runtime?: string;
} | null> {
    const statusKey = `${WARMUP_STATUS_PREFIX}${examId}`;
    const status = await redisConnection.get(statusKey);

    if (!status) {
        return { isWarm: false };
    }

    try {
        const parsed = JSON.parse(status);
        return {
            isWarm: true,
            ...parsed,
        };
    } catch {
        return { isWarm: false };
    }
}

/**
 * Get exams that need warmup (starting in next 15 minutes)
 * 
 * Note: Uses Redis to track warmup status instead of DB column
 * to avoid dependency on schema migration.
 */
export async function getExamsNeedingWarmup(): Promise<Array<{
    id: string;
    title: string;
    expectedCandidates: number | null;
    scheduledStartAt: Date | null;
    challenge: {
        runner?: {
            mode?: string;
            runtime?: string;
            candidate?: {
                image?: string;
                generatedFiles?: Record<string, string>;
                installCommand?: string;
            };
            tests?: {
                image?: string;
            };
        } | null;
        dependencies: Record<string, string>;
    };
}>> {
    const now = new Date();
    const warmupWindow = new Date(now.getTime() + 15 * 60 * 1000);

    // Query exams starting in next 15 minutes
    // Don't filter by poolWarmedAt to avoid requiring schema migration
    const upcomingExams = await db.query.exams.findMany({
        where: (exams, { and, gte, lte, isNotNull }) =>
            and(
                isNotNull(exams.scheduledStartAt),
                gte(exams.scheduledStartAt, now),
                lte(exams.scheduledStartAt, warmupWindow)
            ),
        with: {
            challenge: true,
        },
    });

    // Filter out already-warmed exams using Redis status
    const needsWarmup = [];
    for (const exam of upcomingExams) {
        const isWarm = await isExamPoolWarm(exam.id);
        if (!isWarm) {
            // Extract runner config for image and other settings
            const runner = exam.challenge.runner as {
                mode?: string;
                runtime?: string;
                candidate?: {
                    image?: string;
                    generatedFiles?: Record<string, string>;
                    installCommand?: string;
                };
                tests?: {
                    image?: string;
                };
            } | null;
            
            needsWarmup.push({
                id: exam.id,
                title: exam.title,
                expectedCandidates: (exam as unknown as { expectedCandidates?: number }).expectedCandidates ?? null,
                scheduledStartAt: exam.scheduledStartAt,
                challenge: {
                    runner,
                    dependencies: (exam.challenge.dependencies || {}) as Record<string, string>,
                },
            });
        }
    }

    return needsWarmup;
}

/**
 * Auto-warmup check (called by scheduler)
 */
export async function runAutoWarmup(): Promise<number> {
    const examsNeedingWarmup = await getExamsNeedingWarmup();

    if (examsNeedingWarmup.length === 0) {
        return 0;
    }

    console.log(`[Warmer] Found ${examsNeedingWarmup.length} exams needing warmup`);

    let warmedCount = 0;
    for (const exam of examsNeedingWarmup) {
        try {
            const result = await warmPoolForExam({
                examId: exam.id,
                expectedCandidates: exam.expectedCandidates || 100,
                runnerMode: exam.challenge.runner?.mode,
                runtime: exam.challenge.runner?.runtime || 'node',
                challengeDependencies: exam.challenge.dependencies,
                candidateImage: exam.challenge.runner?.candidate?.image,
                testsImage: exam.challenge.runner?.tests?.image,
                generatedFiles: exam.challenge.runner?.candidate?.generatedFiles,  // <-- For dep pre-install!
                installCommand: exam.challenge.runner?.candidate?.installCommand,   // <-- For dep pre-install!
            });

            if (result.success) {
                warmedCount++;
            }
        } catch (error) {
            console.error(`[Warmer] Failed to warm pool for exam ${exam.id}:`, error);
        }
    }

    return warmedCount;
}
